package try_catch_part2;

public class Test 
{
public static void main(String[] args) 
{
try
{
	
	
}

catch(ArithmeticException e)
{
	
System.out.println(e);	
}
finally
{
	System.out.println();
}
}
}
